site_name: Aplos Console

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Manual: manual.md
  - Changelog: changelog.md
  - About: about.md
  - Console:
      - Overview: console.md
      - AplosConsole: aplos-console.md
      - AplosWindowManager: aplos-window-manager.md
      - AplosWindowSettings: aplos-window-settings.md
  - Command System:
      - AplosDebugCommand: aplos-debug-command.md
      - Interfaces: command-system-interfaces.md
  - Color Picker:
      - AplosColorPickerView: aplos-color-picker-view.md
  - Settings:
      - AplosSettingsManager: aplos-settings-manager.md
  - Input:
      - AplosInputManager: aplos-input-manager.md
