site_name: Aplos Console

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Manual: manual.md
  - Console:
      - Overview: console.md
      - AplosConsole: aplos-console.md
      - AplosInputManager: aplos-input-manager.md
      - AplosSettingsManager: aplos-settings-manager.md
      - AplosWindowManager: aplos-window-manager.md
      - AplosWindowSettings: aplos-window-settings.md
  - Changelog: changelog.md
  - About: about.md
