site_name: Aplos Console

theme:
  name: readthedocs

extra_css:
  - css/extra.css

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Manual: manual.md
  - Changelog: changelog.md
  - About: about.md
  - Console:
      - Overview: console.md
      - AplosConsole: aplos-console.md
      - AplosConsoleCommandConstructor: aplos-console-command-constructor.md
      - Interfaces: console-interfaces.md
  - Window:
      - AplosWindowManager: aplos-window-manager.md
      - AplosWindowRequest: aplos-window-request.md
      - AplosWindowSettings: aplos-window-settings.md
      - Interfaces: window-interfaces.md
  - Command System:
      - AplosDebugCommand: aplos-debug-command.md
      - Interfaces: command-system-interfaces.md
  - Color Picker:
      - AplosColorPickerView: aplos-color-picker-view.md
      - Interfaces: color-picker-interfaces.md
  - Settings:
      - AplosSettingsManager: aplos-settings-manager.md
      - Interfaces: settings-interfaces.md
  - Attributes:
      - DebugSettingAttribute: debug-setting-attribute.md
      - DebugGroupAttribute: debug-group-attribute.md
  - Input:
      - AplosInputManager: aplos-input-manager.md
      - AplosConsoleInputAdapterBase: aplos-console-input-adapter-base.md
      - Interfaces: input-interfaces.md
